export const VOCAB_SUBJECT_KEYS = {
  GET_VOCAB_SUBJECT: 'GET_VOCAB_SUBJECT',
  REORDER_VOCAB_SUBJECT: 'REORDER_VOCAB_SUBJECT',
  POST_VOCAB_SUBJECT: 'POST_VOCAB_SUBJECT',
  DELETE_VOCAB_SUBJECT: 'DELETE_VOCAB_SUBJECT',
  UPDATE_VOCAB_SUBJECT: 'UPDATE_VOCAB_SUBJECT'
}
