export const languageList = [
  { label: "Korean", value: "ko" },
  { label: "Vietnamese", value: "vi" },
  { label: "English", value: "en" },
];

export const wordTypeList = [
  { label: "Noun (Danh từ)", value: "Noun" },
  { label: "Verb (Động từ)", value: "Verb" },
  { label: "Adverbs (Trạng từ)", value: "Adverbs" },
  { label: "Adjective (Tính từ)", value: "Adjective" },
  { label: "Pronouns (Đại từ)", value: "Pronouns" },
  { label: "Interjection (Thán từ)", value: "Interjection" },
  { label: "Conjunction (Liên từ)", value: "Conjunction" },
  { label: "Preposition (Giới từ)", value: "Preposition" },
  { label: "Auxiliary words (Trợ từ)", value: "Auxiliary words" },
];

export const subjectList = [
  { label: "Career (Nghề nghiệp)", value: "Career" },
  { label: "Clothing (Quần áo)", value: "Clothing" },
  { label: "Animals (Con vật)", value: "Animals" },
  {
    label: "Fruits and Vegetables (Rau củ quả)",
    value: "Fruits and Vegetables",
  },
  { label: "Human Body (Cơ thể người)", value: "Human Body" },
  { label: "Transportation (Giao thông)", value: "Transportation" },
  { label: "Food (Đồ ăn)", value: "Food" },
  { label: "Music (Âm nhạc)", value: "Music" },
  { label: "Beverages (Đồ uống)", value: "Beverages" },
  { label: "Flowers (Hoa)", value: "Flowers" },
  { label: "Culture (Văn hóa)", value: "Culture" },
  { label: "Skills (Kỹ năng)", value: "Skills" },
  { label: "Health (Sức khỏe)", value: "Health" },
  { label: "Family (Gia đình)", value: "Family" },
  { label: "Technology (Công nghệ)", value: "Technology" },
  { label: "Travel (Du lịch)", value: "Travel" },
  { label: "Education (Giáo dục)", value: "Education" },
  { label: "Hobbies (Sở thích)", value: "Hobbies" },
  { label: "Entertainment (Giải trí)", value: "Entertainment" },
  { label: "Relationships (Mối quan hệ)", value: "Relationships" },
  { label: "Beauty (Làm đẹp)", value: "Beauty" },
  { label: "Shopping (Shopping)", value: "Shopping" },
  { label: "Kitchen (Nhà bếp)", value: "Kitchen" },
  { label: "City (Thành phố)", value: "City" },
  { label: "Tet (Tết)", value: "Tet" },
  { label: "School (Trường học)", value: "School" },
  { label: "Soccer (Bóng đá)", value: "Soccer" },
  { label: "Environment (Môi trường)", value: "Environment" },
  { label: "Sports (Thể thao)", value: "Sports" },
  { label: "Christmas (Giáng sinh)", value: "Christmas" },
  { label: "Cooking (Nấu ăn)", value: "Cooking" },
  { label: "Emotions (Cảm xúc)", value: "Emotions" },
  { label: "Lifestyle (Đời sống)", value: "Lifestyle" },
  { label: "Law (Luật pháp)", value: "Law" },
  { label: "Fashion (Thời trang)", value: "Fashion" },
  { label: "Business (Kinh doanh)", value: "Business" },
  { label: "Mobile Phones (Điện thoại di động)", value: "Mobile Phones" },
  { label: "Work (Làm việc)", value: "Work" },
  { label: "Personality (Tính cách)", value: "Personality" },
  { label: "Home (Nhà cửa)", value: "Home" },
  { label: "Time (Thời gian)", value: "Time" },
  { label: "Company (Công ty)", value: "Company" },
  { label: "Office Life (Đời sống công sở)", value: "Office Life" },
  { label: "Art (Nghệ thuật)", value: "Art" },
  {
    label: "Computers and Networks (Máy tính và Mạng)",
    value: "Computers and Networks",
  },
  {
    label: "Phones and Messaging (Điện thoại và Thư tín)",
    value: "Phones and Messaging",
  },
];

export const defaultValue = {
  text: "",
  wordType: "Verb",
  explanationSource: "",
  explanationTarget: "",
  grammar: "",
  subject: [],
};
