export const VOCAB_TRAINER_KEYS = {
  GET_VOCAB_TRAINER: "GET_VOCAB_TRAINER",
  POST_VOCAB_TRAINER: "POST_VOCAB_TRAINER",
  DELETE_VOCAB_TRAINER: "DELETE_VOCAB_TRAINER",
  UPDATE_VOCAB_TRAINER: "UPDATE_VOCAB_TRAINER",
};
