export const NOTIFICATION_KEYS = {
  GET_NOTIFICATION: 'GET_NOTIFICATION',
  GET_UNREAD_NOTIFICATION: 'GET_UNREAD_NOTIFICATION',
  GET_UNREAD_COUNT_NOTIFICATION: 'GET_UNREAD_COUNT_NOTIFICATION',
  PUT_MARK_NOTIFICATION: 'PUT_MARK_NOTIFICATION',
}
